drop table if exists raw_data;
CREATE TABLE `raw_data` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `season_year` int(11) NOT NULL,
  `game_string` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `game_date` datetime NOT NULL,
  `game_type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `visitor` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `home` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `visiting_team_final_runs` int(11) NOT NULL,
  `home_team_final_runs` int(11) NOT NULL,
  `inning` int(11) NOT NULL,
  `side` varchar(1) COLLATE utf8_unicode_ci NOT NULL,
  `batter_id` int(10) unsigned NOT NULL,
  `batter` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `batter_hand` varchar(1) COLLATE utf8_unicode_ci NOT NULL,
  `pitcher_id` int(10) unsigned NOT NULL,
  `pitcher` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `pitcher_hand` varchar(1) COLLATE utf8_unicode_ci NOT NULL,
  `catcher_id` int(11) NOT NULL,
  `catcher` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `times_faced` int(11) NOT NULL,
  `batter_pos` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `balls` smallint(6) NOT NULL,
  `strikes` smallint(6) NOT NULL,
  `outs` smallint(6) NOT NULL,
  `man_on_first` varchar(255) NOT NULL,
  `man_on_second` varchar(255) NOT NULL,
  `man_on_third` varchar(255) NOT NULL,
  `end_man_on_first` varchar(255) NOT NULL,
  `end_man_on_second` varchar(255) NOT NULL,
  `end_man_on_third` varchar(255) NOT NULL,
  `visiting_team_current_runs` int(11) NOT NULL,
  `home_team_current_runs` int(11) NOT NULL,
  `pitch_result` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `pitch_type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `release_velocity` decimal(5,2) NOT NULL,
  `spin_rate` decimal(7,3) NOT NULL,
  `spin_direction` decimal(7,4) NOT NULL,
  `px` decimal(7,4) NOT NULL,
  `pz` decimal(6,4) NOT NULL,
  `szt` decimal(6,4) NOT NULL,
  `szb` decimal(6,4) NOT NULL,
  `x0` decimal(6,4) NOT NULL,
  `y0` int(11) NOT NULL,
  `z0` decimal(6,4) NOT NULL,
  `vx0` decimal(6,4) NOT NULL,
  `vy0` decimal(7,4) NOT NULL,
  `vz0` decimal(6,4) NOT NULL,
  `ax` decimal(7,4) NOT NULL,
  `ay` decimal(6,4) NOT NULL,
  `az` decimal(6,4) NOT NULL,
  `pa_result` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `runs_home` int(11) NOT NULL,
  `batted_ball_type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `batted_ball_angle` decimal(5,3) NOT NULL,
  `batted_ball_distance` decimal(6,3) NOT NULL,
  `atbat_desc` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `timestamp_utc` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`)
);

LOAD DATA LOCAL INFILE '/Users/murribu/Google\ Drive/TruMedia/2013.csv'
INTO TABLE raw_data
FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
  `season_year`,
  `game_string` ,
  `game_date` ,
  `game_type` ,
  `visitor` ,
  `home` ,
  `visiting_team_final_runs` ,
  `home_team_final_runs` ,
  `inning` ,
  `side` ,
  `batter_id` ,
  `batter` ,
  `batter_hand` ,
  `pitcher_id` ,
  `pitcher` ,
  `pitcher_hand` ,
  `catcher_id` ,
  `catcher` ,
  `times_faced` ,
  `batter_pos` ,
  `balls` ,
  `strikes` ,
  `outs` ,
  `man_on_first` ,
  `man_on_second` ,
  `man_on_third` ,
  `end_man_on_first` ,
  `end_man_on_second` ,
  `end_man_on_third` ,
  `visiting_team_current_runs` ,
  `home_team_current_runs` ,
  `pitch_result` ,
  `pitch_type` ,
  `release_velocity`,
  `spin_rate` ,
  `spin_direction` ,
  `px` ,
  `pz` ,
  `szt` ,
  `szb` ,
  `x0` ,
  `y0` ,
  `z0` ,
  `vx0` ,
  `vy0` ,
  `vz0` ,
  `ax` ,
  `ay` ,
  `az` ,
  `pa_result` ,
  `runs_home` ,
  `batted_ball_type` ,
  `batted_ball_angle` ,
  `batted_ball_distance` ,
  `atbat_desc` ,
  `timestamp_utc`);

LOAD DATA LOCAL INFILE '/Users/murribu/Google\ Drive/TruMedia/2014.csv'
INTO TABLE raw_data
FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
  `season_year`,
  `game_string` ,
  `game_date` ,
  `game_type` ,
  `visitor` ,
  `home` ,
  `visiting_team_final_runs` ,
  `home_team_final_runs` ,
  `inning` ,
  `side` ,
  `batter_id` ,
  `batter` ,
  `batter_hand` ,
  `pitcher_id` ,
  `pitcher` ,
  `pitcher_hand` ,
  `catcher_id` ,
  `catcher` ,
  `times_faced` ,
  `batter_pos` ,
  `balls` ,
  `strikes` ,
  `outs` ,
  `man_on_first` ,
  `man_on_second` ,
  `man_on_third` ,
  `end_man_on_first` ,
  `end_man_on_second` ,
  `end_man_on_third` ,
  `visiting_team_current_runs` ,
  `home_team_current_runs` ,
  `pitch_result` ,
  `pitch_type` ,
  `release_velocity`,
  `spin_rate` ,
  `spin_direction` ,
  `px` ,
  `pz` ,
  `szt` ,
  `szb` ,
  `x0` ,
  `y0` ,
  `z0` ,
  `vx0` ,
  `vy0` ,
  `vz0` ,
  `ax` ,
  `ay` ,
  `az` ,
  `pa_result` ,
  `runs_home` ,
  `batted_ball_type` ,
  `batted_ball_angle` ,
  `batted_ball_distance` ,
  `atbat_desc` ,
  `timestamp_utc`);

LOAD DATA LOCAL INFILE '/Users/murribu/Google\ Drive/TruMedia/2015.csv'
INTO TABLE raw_data
FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
  `season_year`,
  `game_string` ,
  `game_date` ,
  `game_type` ,
  `visitor` ,
  `home` ,
  `visiting_team_final_runs` ,
  `home_team_final_runs` ,
  `inning` ,
  `side` ,
  `batter_id` ,
  `batter` ,
  `batter_hand` ,
  `pitcher_id` ,
  `pitcher` ,
  `pitcher_hand` ,
  `catcher_id` ,
  `catcher` ,
  `times_faced` ,
  `batter_pos` ,
  `balls` ,
  `strikes` ,
  `outs` ,
  `man_on_first` ,
  `man_on_second` ,
  `man_on_third` ,
  `end_man_on_first` ,
  `end_man_on_second` ,
  `end_man_on_third` ,
  `visiting_team_current_runs` ,
  `home_team_current_runs` ,
  `pitch_result` ,
  `pitch_type` ,
  `release_velocity`,
  `spin_rate` ,
  `spin_direction` ,
  `px` ,
  `pz` ,
  `szt` ,
  `szb` ,
  `x0` ,
  `y0` ,
  `z0` ,
  `vx0` ,
  `vy0` ,
  `vz0` ,
  `ax` ,
  `ay` ,
  `az` ,
  `pa_result` ,
  `runs_home` ,
  `batted_ball_type` ,
  `batted_ball_angle` ,
  `batted_ball_distance` ,
  `atbat_desc` ,
  `timestamp_utc`);